### PR TITLE
CODE REVIEW FOR mockup documentation Before building Facebook app

### PR DESCRIPTION
**Pull request by shloch**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi Team,
Good start with docs. Just minor naming change. `Follower` is confusing for this sort of app, it should be `Friend_request` and `friend_respond` or any other name you think is making better sense.
Let's update and submit for review.

**Comment by shloch** [comment]
Thank you for the suggestion....we modified the documentation

**Review by inhaq — CHANGES_REQUESTED** [review]
There is still `followers` and `followees` words, kindly update it with meaningful words. These words are from twitter which works differently than `FB`.

**Comment by shloch** [comment]
We brought about adjustments...thanks

**Review by inhaq — APPROVED** [review]
Looks good, let's move to the next part of the project. It's 👍🏻for docs

**Pull request merged**
