### PR TITLE
Controllers

### PR DESCRIPTION
**Pull request by shloch**
Requesting for review:

We have finished almost every thing, except TESTING, which we'll continue starting tomorrow
We have a major concern  though regarding authentication with OMNIAUTH. We have followed multiple tutorials and we're sure to have implemented it correctly. But we still have this consistent issue as stated in this feed (by another user) : 

---> https://github.com/omniauth/omniauth/issues/816
(we're redirected back to the register page)

We have searched online for days, we dont know why ....

One of the best tutorials we used followed for omniauth is --> https://github.com/rails-camp/facebook-omniauth-demo

Anyways, we still want to submit for review so that we can get feedback whether we're on the right track on all other aspects. 

Also, while we where working on this project, modifications where being done on the instructions on the dashboard by MICROVERSE. So we couldn't quite follow the steps chronologically, but we still have covered all the core tasks necessary, as the project demands.

Thanks

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Awesome work. Here are a few things needs to be updated/fixed:
 - UI needs fixes, lots of stuff aren't looking good(optional but will be great for portfolio though)
 - The post shouldn't be added if empty
 - Comment should be allowed to delete by Post owner
 - The post should be allowed to delete
 - Like should be removed while clicking on it again
 - Click on notification icon is not working when clicking the second time
 - User should be able to see friends profile

Let's make these changes(or let me know on slack if you've questions) and resubmit for review.

**Review by inhaq — APPROVED** [review]
Good job on fixes.
 - On the UI part, when I entered the wrong info. [It just broke the layout](https://snag.gy/hsqUyJ.jpg).
 - Like still can't be clicked to remove the like.
Both these are changes for next iteration, you guys can go ahead with testing as well. 👍🏻

**Comment by pwilson77** [comment]
Added tests to the project. Testing was done with RSPEC and changes styling changes were done to the parts of the layout that was broken

**Comment by dipto0321** [comment]
Hi @shloch and @pwilson77 ,

Good job guys 👏 . Project looks good. Currently, I am having this problem
.

This is happening because there is a validation for `:mobile` in the user model. But in seed file, I didn't see any `:mobile` parameter when it tries to create some demo users. So please fix that. You already added some test using Rspec. Here is a couple of things I want to mention it's up to you if you want to implement those right now or later. 
   - Postgresql is the best database choice for this kind of big project. So please try to use postgress not only for production. For the whole project. Even you just added pg in production but I didn't see it actually use.
  - Add test for all models and features as much as possible.
  
That's it. This is from me 👍 .

Thanks 🙏

**Comment by shloch** [comment]
Hello @dipto0321 , sorry, we had to empty that seed file, we were actually using but FactoryBot, to generate test data, not the seed file.

So you can see the test data here --> https://github.com/shloch/Building_Facebook/blob/controllers/spec/factories/user.rb

Thanks for the contributions

**Comment by dipto0321** [comment]
Hi @shloch ,

Yeah. I checked all the things. it's okay. Only have problem with seed.rb. So if you planed to clear those seed then go for it. Otherwise, add mobile data into the seeds. Because For the first time I always run `rails db:setup` command. What it actually did it's set up my local database for test and development and also it checks if there are any seeds then it also implements those to the database. During this process, if there any task failed means the whole process failed. That's why I told to fix seeds. Now it's your choice as I said before. You can clear the whole seed.rb codes or you can add a mobile parameter so that it can generate random user with mobile number. 🙂  That's it.

Thanks 🙏

**Comment by shloch** [comment]
Thank you, i see what you talking about now. Sorry i confused seed.rb file with fixtures :) 
We're still trying to master all the concepts.

I just modified the seed file

Thank you @dipto0321 

we're open for all contributions

**Pull request merged**
